language: node_js
node_js: stable
before_script:
- npm install --silent bower polymer-cli
- "./node_modules/.bin/bower install --silent"
addons:
  sauce_connect: true
script:
- npm run lint
- ./node_modules/.bin/polymer test --plugin sauce --job-name "raml-type-form-behavior:${TRAVIS_BRANCH}"
  --build-number=${TRAVIS_BUILD_NUMBER}
after_success:
- node tasks/ci.js
env:
  global:
  - secure: TrCx+UbeaGmaXoWbODKzaL6ycmR5v6HFNhGFlzUP+z6SC4F/KAoT9TtgPjST24Toct0nbnSIkzdiYQxqpwXA2jzGkMrZ1B9L09l7OuJsq75Rp0L5zSFdUqLZEk+3TXVEuBY6DDXzZGxR46OaW/wBMAAn+kMxnzg0Y+vbjBE6PuUQbByULz70TU/faS1SEqFcXUcrwFH1awfoxVW6nVy8eue+e+AkKEpFdLL7SHhHbXqAN6lpLe8fnj6WBU0QUbIn8DlZ1aEuAHGiCnmB/vI9C3k7oMLDFHpaXhUcPpMxGySPwL+9TJTJWSb5ae38U7mlQdmMJlrw0K8XtFn2QvK6Eukg8xgqEHQ3lI0uvoj7wA4AyaSBQtOqS1ow8yikC3IHwMRT6yv6jT8LD7n2fQunjcLhXc92q95Uo31Hz2syacUMcVijgYLi00HzhnlLoLoOKMcmTSgGPvydqmQaeK1gIhwMYSLy9WOiIKFcvYH0c64R0EvfDfKsiq98fLfPSr5z28mZOU8yNDOYEmfNizNMSl85NDY80DmQDBJuH9+rv3sW+mcvOijXPIgyeo45GoOBtBXMU5ovYnYCrvCkSxtHa2HY7c1d+EPGszEztkZYL0/gr+ZHSlyjHwADM0blWh8khN1CnQR9oOdCUBt/WNpoE1RMjc6pWxJQ0oIp3ZLKy3g=
  - secure: LjwyOPoGDOEsv8eVbUZPGdQrMoJx4BVGyZ3KlTa2UBFk9Rq4alyzIohlCMhZ1udrANx3fPPUL8+/p6TF/u5In7mtg0GpoDq2ZRepHxDl/A6nWU/c7cZVCouNCH3Z67CAYtv2HWx97BCmTCKCiVjzCAL+o4ffI392AvMkgcBsJnlNBAdIZspPS/g43xSGDjJg2rw+oUMIVep8dMVN7j4ezUfAjltacFMxHy8E/FNVG0/D4NIKkKQDjklro1IYjfKSOBLoJHOxylXKsKtfJQF+KpcUMyYfFrJ3DW2jc5325wPpd1sNZTrh9skNdNSVILGa6Gbb8mpI/N0dHDYN4/GnivBqwEx7gx/epM8grxjwu7RIToFSDEVGZ4/Qk5zO7bHHMUM6IVCYi2wP87CWzER2cmnmXRTpkFGw5lIFPFKwVcRVr588pdSCp9L8DEtwPs/rddS2QVajgDS4kRwxi/R5ccSR4LRh2GRrvHP+rRR1m5Q1E8o+lodPYMy88GhLWpG6nbnbc/cUbgFbh/c1vRCdJll0mDVnr95pTojXmlatjKSym52VnkVX1S66SrxF1iTOACZz5B72aFW2Ivq69q8aKCoSDSWU0Ek5cGy09SEr0vAsjjkvOs/4j3y9rNKCyelTZj8ZSfidc3elm1nnDYUw8CgVodMCosnJh/hPsxpECdE=
